# Generated by Django 3.1.4 on 2020-12-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectionApp', '0003_auto_20201226_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyidentity',
            name='verified',
        ),
        migrations.AlterField(
            model_name='familyidentity',
            name='familyMembers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='familyidentity',
            name='middleName',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
